# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d310b00c919ecf452e63aa5377c4df08f6f9c9d0156c9cb3b1ea121d6c559759f79bdc2e86f69409ab44aac2bd23de39268ef63ba5a3a71f88b106ab9956743

test:
  secret_key_base: 4f271ca5e5ef2651d37f168683b2ac5c21dea22ef32a361b81b0754ca43509dff7d0bd033ae2ce7704288683f9a533d21e8e14feddd4a9b7da25ebbc01bef17f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
